### ISSUE TITLE
의미없는 Fragment 사용

### ISSUE THREAD

**Issue by jake920220** [seokwon27/Rider_project#6]
https://github.com/seokwon27/Rider_project/blob/4875b650e4ff57ca3eaabf9e32fc147aca0ae13c/src/components/Layout.jsx#L1-L13

위 코드에 <div>로 wrapping이 되어있음에도 불구하고 Fragment로 wrapping이 되어있어 issue를 남깁니다! : )

**Comment by kimseoyun98** [comment]
#7 레이아웃 부분 기능 구현해서 pr올렸습니다! 감사합니다

**Comment by jake920220** [comment]
> #7 레이아웃 부분 기능 구현해서 pr올렸습니다! 감사합니다

어제 이슈 생성 예시로 보고 올린 코드였는데 확인하고 수정하시느라 고생많으셨어요~~!! : )
